### ISSUE TITLE
Roto addon hangs when I hit the generate button

### ISSUE THREAD

**Issue by 3pointedit** [MagnumVD/RotoForge-AI#1]
I installed the dependencies downloads in a reconstructed path as my machine doesn't allow access to the internet. I made sure to copy it from the internet connected machine but the root path is not identical. However the addon did run after activating it. And it works in the image viewer window. Until I click on the Generate or track buttons. I couldn't find the session log, and there's no error in the python console. I grabbed this photo of the error message and here is the Cuda settings for the machine.
![20240518_185117](https://github.com/MagnumVD/RotoForge-AI/assets/25983373/0d489aec-d508-40b0-957d-312b2fd3ce09)
![20240518_185148](https://github.com/MagnumVD/RotoForge-AI/assets/25983373/44624685-ee66-4d16-9225-04d14f8936d9)

Blender 4.1 alpha (sorry i know this part is less than ideal)

**Comment by MagnumVD** [comment]
That's a very weird error... Can you try different cuda settings on your device?
I'd like to see if a different outcome happens when:
-you deselect your cpu.
-you remove cuda entirely, you can switch either to optix or none.

Theoretically the addon runs independent from the blender cuda settings, but I'd like to see if there are maybe conflicting problems if both blender and the addon run on cuda.

**Comment by 3pointedit** [comment]
CUDA on CPU off=crash
CUDA off CPU off=crash
OPTIX on Nvidia a 5000 off =crash
Nothing else is using the card except for the monitors
Same crash report

**Comment by 3pointedit** [comment]
Cycles settings NONE selected = crash

**Comment by 3pointedit** [comment]
Looking at[ this entry](https://github.com/nanoporetech/bonito/issues/287) In Bleender's Py console I tried the cuda call but it doesn't import?
`>>> import torch
>>> print(torch.__version__)
2.2.2+cu121

>>> print(torch.cuda.is_available())
False

>>> `

**Comment by 3pointedit** [comment]
Our Nvidia driver is circa December 2021. Could that be an problem?

**Comment by 3pointedit** [comment]
Just got told that driver upgrade is very unlikely :( enterprise systems are fragile

**Comment by MagnumVD** [comment]
Just looked it up, you couldn't even use cuda 11.8, since it was released in 2022.
What I can implement for the next version is a small checkbox which forces a pytorch download for cpu only usage so you can use it. But other than that, I think we need to call it failed.

Could you still provide me the details on which data you needed to transfer to get the base addon working? I'd like to put up a small tutorial for that.

**Comment by 3pointedit** [comment]
When I downloaded from the addon on the PC with internet access (but no Nvidia card) I ended up with 2 new folders in my download folder:  py_packages : sam_hq_weights
I put them in the root user path as directed in the addon's install window but i had to reconstruct it as \MVD-addons dependencies\RotoForge AI\
After rebooting Blender I could press the install button and the packages were recognized but it takes a while to load them. I was able to do the same thing on the Nvidia machine, which doesn't have internet access, by running the addon and making the path as instructed, then copying the folders across to their new home.

**Comment by MagnumVD** [comment]
Oh wow, that seems easier than I thought.
Thanks👍 
If you have the opportunity I'd also like to take a look at the downloads in the wrong directory thing. Could you create a new issue for that?

I think we can close this one.
